name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_FOLDER: 'CleanArchitecture.SharedLibrary'
  PROJECT_FILE_NAME: 'CleanArchitecture.SharedLibrary.csproj'
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}/artefacts
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/Kode4Hue/index.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Dotnet Restore dependencies
      run: dotnet restore
    - name: Dotnet Build Project
      run: dotnet build ${{ env.PACKAGE_OUTPUT_DIR }}\${{ env.PROJECT_FILE_NAME }} --configuration Release
    - name: Package the library
      run: dotnet pack --configuration Release --no-restore --nobuild --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIR }}
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
    - name: Publish the Package to Github
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIR }}\*.nupkg -s ${{ env.NUGET_SOURCE_URL }}
